digma-ai/digma-ui

- .storybook/preview.tsx
- package-lock.json
- package.json
- src/components/Assets/AssetList/index.tsx
- src/components/Assets/AssetList/styles.ts
- src/components/Assets/AssetList/types.ts
- src/components/Assets/AssetTypeList/types.ts
- src/components/RecentActivity/RecentActivityTable/types.ts
- src/components/RecentActivity/types.ts
- src/components/common/App/index.tsx
- src/components/common/App/types.ts
- src/components/common/AssetEntry/AssetEntry.stories.tsx
- src/components/common/AssetEntry/index.tsx
- src/components/common/AssetEntry/types.ts
- src/components/common/Menu/Menu.stories.tsx
- src/components/common/Menu/index.tsx
- src/components/common/Menu/styles.ts
- src/components/common/Menu/types.ts
- src/components/common/Popover/PopoverContent/index.tsx
- src/components/common/Popover/PopoverContent/types.ts
- src/components/common/Popover/PopoverTrigger/index.tsx
- src/components/common/Popover/PopoverTrigger/styles.ts
- src/components/common/Popover/PopoverTrigger/types.ts
- src/components/common/Popover/hooks.ts
- src/components/common/Popover/index.tsx
- src/components/common/Popover/types.ts
- src/environment.ts
- src/globals.d.ts
Add sorting menu to the Assets page Closes #17 
Add theme toolbar to Storybook
> Add sorting menu to the Assets page

- src/components/Assets/AssetList/index.tsx
- src/components/Assets/AssetList/styles.ts
- src/components/RecentActivity/RecentActivityTable/index.tsx
- src/components/RecentActivity/RecentActivityTable/types.ts
- src/components/RecentActivity/index.tsx
Pass environment with the span data on link click in Recent Activity (relates to [issue 349](https://github.com/digma-ai/digma-intellij-plugin/issues/349))
> Fix sorting in Assets page

- src/components/common/App/styles.ts
> Apply browser color scheme according to the IDE theme

- .storybook/preview-body.html
- assets/installationWizard/index.ejs
- src/components/InstallationWizard/Button/styles.ts
- src/components/InstallationWizard/CodeSnippet/styles.ts
- src/components/InstallationWizard/index.tsx
- src/components/InstallationWizard/styles.ts
- src/globals.d.ts
Update Installation Wizard styles Fixes #33 
Add environment variable to skip installation step
> Update Installation Wizard styles

- .storybook/preview-body.html
- src/components/RecentActivity/RecentActivityTable/index.tsx
- src/components/RecentActivity/RecentActivityTable/types.ts
- src/components/RecentActivity/index.tsx
- src/components/RecentActivity/types.ts
- src/globals.d.ts
> Hide Trace button in Recent activity if Jaeger is not enabled

- src/components/RecentActivity/RecentActivity.stories.tsx
- src/components/RecentActivity/RecentActivityTable/index.tsx
> Sort activity entries in Recent activity

- src/components/RecentActivity/EnvironmentPanel/styles.ts
- src/components/RecentActivity/LiveView/AreaTooltipContent/index.tsx
- src/components/RecentActivity/LiveView/AreaTooltipContent/styles.ts
- src/components/RecentActivity/LiveView/AreaTooltipContent/types.ts
- src/components/RecentActivity/LiveView/ChangeStatus/index.tsx
- src/components/RecentActivity/LiveView/ChangeStatus/styles.ts
- src/components/RecentActivity/LiveView/ChangeStatus/types.ts
- src/components/RecentActivity/LiveView/DotTooltipContent/index.tsx
- src/components/RecentActivity/LiveView/DotTooltipContent/styles.ts
- src/components/RecentActivity/LiveView/DotTooltipContent/types.ts
- src/components/RecentActivity/LiveView/LiveView.stories.tsx
- src/components/RecentActivity/LiveView/TooltipContent/styles.ts
- src/components/RecentActivity/LiveView/index.tsx
- src/components/RecentActivity/LiveView/mockData.ts
- src/components/RecentActivity/LiveView/styles.ts
- src/components/RecentActivity/LiveView/types.ts
- src/components/RecentActivity/RecentActivityTable/index.tsx
- src/components/common/Badge/styles.ts
- src/components/common/icons/ArrowIcon.tsx
- src/components/common/icons/ArrowSmallIcon.tsx
- src/components/common/icons/ChartIcon.tsx
- src/components/common/icons/types.ts
- src/types.ts
- src/utils/getInsightTypeInfo.ts
- src/utils/getInsightTypeOrderPriority.ts
Closes #92 
Add "Scroll to the latest data" button
Update styles and and light theme
> Add Change status in Live view

- src/components/Assets/AssetList/AssetEntry/index.tsx
- src/components/InstallationWizard/InstallStep/index.tsx
- src/components/InstallationWizard/InstallStep/types.ts
- src/components/InstallationWizard/index.tsx
- src/components/InstallationWizard/styles.ts
- src/components/InstallationWizard/tracking.ts
Closes #99 
Update prerequisites according to the Docker Marketplace
Do not show empty icons for unknown insights in Assets
> Add "no Docker" tab to Installation Wizard

- src/components/Assets/index.tsx
- src/components/Assets/mockData.ts
- src/components/Assets/types.ts
- src/components/common/Button/styles.ts
- src/components/common/icons/PieChartIcon.tsx
- src/types.ts
- src/utils/getInsightTypeInfo.ts
- src/utils/getInsightTypeOrderPriority.ts
> Add Request Breakdown Insight support

- src/api/ActionDispatcher.ts
- src/api/index.ts
- src/api/types.ts
- src/components/Assets/index.tsx
- src/components/common/App/index.tsx
- src/components/common/CursorFollower/index.tsx
> Fix assets refresh timers

- src/components/Assets/AssetList/AssetEntry/index.tsx
- src/components/Assets/AssetList/AssetEntry/styles.ts
- src/components/Assets/AssetList/index.tsx
- src/components/Assets/AssetList/types.ts
- src/components/Assets/styles.ts
> Add Slowest 5% to Assets

- src/components/RecentActivity/LiveView/LiveView.stories.tsx
- src/components/RecentActivity/LiveView/index.tsx
- src/components/RecentActivity/LiveView/styles.ts
- src/utils/roundToNonZeroDecimals.ts
> Fix Live View chart Y Axis scale

- src/components/InstallationWizard/InstallStep/index.tsx
Show Next button when Digma Engine is already installed  before the first Wizard launch
> Show Next button when Digma Engine is already installed 

- src/components/Documentation/pages/runDigmaWithCommandLine.tsx
- src/components/common/App/styles.ts
> Fix typos in docs

- src/components/InstallationWizard/InstallStep/index.tsx
> Show Auto install tab after the installation failure

- src/components/Assets/AssetList/AssetEntry/index.tsx
- src/components/Assets/AssetList/index.tsx
Fix handling of empty list of assets
> Filter visible insights

- src/components/Assets/AssetList/index.tsx
- src/components/Insights/RequestBreakdownInsight/RequestBreakdownInsight.stories.tsx
- src/components/Insights/RequestBreakdownInsight/index.tsx
- src/components/Troubleshooting/index.tsx
- src/components/Troubleshooting/styles.ts
- src/constants.ts
Closes #160 
Update the Getting Started video
Update styles
> Fix async operation fraction

- src/components/Insights/DurationInsight/index.tsx
- src/components/InstallationWizard/InstallStep/index.tsx
- src/components/InstallationWizard/index.tsx
> Remove the Observability step from the Installation Wizard

- src/components/Assets/AssetList/styles.ts
- src/components/Insights/DurationChange/styles.ts
- src/components/Insights/DurationInsight/DurationInsight.stories.tsx
- src/components/Insights/DurationInsight/ReferenceLineLabel/index.tsx
- src/components/Insights/DurationInsight/ReferenceLineLabel/types.ts
- src/components/Insights/DurationInsight/XAxisTick/index.tsx
- src/components/Insights/DurationInsight/XAxisTick/types.ts
- src/components/Insights/DurationInsight/constants.ts
- src/components/Insights/DurationInsight/index.tsx
- src/components/Insights/DurationInsight/styles.ts
- src/components/Insights/DurationInsight/types.ts
- src/components/Insights/DurationSlowdownSourceInsight/index.tsx
- src/components/Insights/DurationSlowdownSourceInsight/styles.ts
- src/components/Insights/Insights.stories.tsx
- src/components/Insights/types.ts
> Add min and max ticks

- src/components/Assets/AssetList/index.tsx
- src/components/Insights/DurationInsight/ReferenceLineLabel/index.tsx
- src/components/Insights/DurationInsight/ReferenceLineLabel/types.ts
- src/components/Insights/DurationInsight/XAxisTick/index.tsx
- src/components/Insights/DurationInsight/index.tsx
- src/components/Insights/DurationInsight/types.ts
- src/components/RecentActivity/LiveView/index.tsx
- src/utils/convertToDuration.ts
- src/utils/convertToDurationUnit.ts
Closes #199 
Closes #197 
Make asset search case insensitive
> Fix Duration chart labels

- src/components/Insights/EndpointNPlusOneInsight/styles.ts
- src/components/Insights/NPlusOneInsight/styles.ts
> Fix insight styles

- src/components/Insights/DurationInsight/index.tsx
> Hide average stats in Duration insight if it zero

- src/components/Insights/index.tsx
- src/components/InstallationWizard/FinishStep/index.tsx
- src/components/InstallationWizard/tracking.ts
- src/components/Notifications/index.tsx
- Getting Started video link in Installation Wizard Closes #207 
- View All link in Notifications
> Add tracking events

- src/components/Insights/Insights.stories.tsx
- src/components/Insights/index.tsx
- src/components/Insights/styles.ts
- src/components/Notifications/FullView/index.tsx
- src/components/Notifications/FullView/styles.ts
- src/components/Notifications/FullView/types.ts
- src/components/Notifications/RecentView/index.tsx
- src/components/Notifications/RecentView/styles.ts
- src/components/Notifications/RecentView/types.ts
- src/components/Notifications/index.tsx
- src/components/common/CircleLoader/index.tsx
- src/components/common/CircleLoader/types.ts
> Fix loader flickering

- src/components/Insights/NPlusOneInsight/index.tsx
> Trim endpoint scheme

- src/components/Assets/AssetList/AssetEntry/index.tsx
- src/components/Assets/AssetList/AssetEntry/styles.ts
> Add tooltip with impact raw value

- src/components/RecentActivity/EnvironmentPanel/EnvironmentTab/index.tsx
> Allow environment deletion if it's not pending

- src/components/InstallationWizard/InstallStep/EngineManager/index.tsx
- src/hooks/useDebounce.ts
> Hide Engine instructions when installation is not allowed

- src/components/Assets/AssetList/AssetEntry/index.tsx
- src/components/Assets/AssetList/AssetEntry/styles.ts
- src/components/Assets/AssetList/AssetEntry/types.ts
- src/components/Assets/AssetList/index.tsx
- src/components/Assets/mockData.ts
> Add asset score indicator

- src/components/Assets/AssetList/AssetEntry/types.ts
- src/components/Assets/AssetList/index.tsx
- src/components/Assets/AssetList/types.ts
- src/components/Assets/AssetTypeList/index.tsx
- src/components/Assets/AssetTypeList/types.ts
- src/components/Assets/index.tsx
- src/components/Assets/types.ts
> Fix asset count

- package-lock.json
- package.json
- src/components/common/App/styles.ts
- src/utils/trimEndpointScheme.ts
Closes #267 
Update dependencies
> Trim endpoint prefix

- src/components/Insights/InsightList/index.tsx
> Fix insight grouping

- src/components/InstallationWizard/InstallStep/index.tsx
- src/components/InstallationWizard/tracking.ts
> Add tracking event for the auto-installation not being started

- src/components/RecentActivity/LiveView/LiveView.stories.tsx
- src/components/RecentActivity/LiveView/index.tsx
> Fix live view when all records have errors

- src/components/Insights/EndpointNPlusOneInsight/EndpointNPlusOneInsight.stories.tsx
- src/components/Insights/EndpointNPlusOneInsight/index.tsx
- src/components/Insights/EndpointNPlusOneInsight/mockData.ts
- src/components/Insights/EndpointNPlusOneInsight/styles.ts
- src/components/Insights/InsightList/index.tsx
- src/components/Insights/InsightList/types.ts
- src/components/Insights/Insights.stories.tsx
- src/components/Insights/JiraTicket/JiraTicket.stories.tsx
- src/components/Insights/JiraTicket/index.tsx
- src/components/Insights/JiraTicket/types.ts
- src/components/Insights/NPlusOneInsight/index.tsx
- src/components/Insights/NPlusOneInsight/mockData.ts
- src/components/Insights/NPlusOneInsight/styles.ts
- src/components/Insights/index.tsx
- src/components/Insights/tickets/EndpointNPlusOneInsightTicket/EndpointNPlusOneTicket.stories.tsx
- src/components/Insights/tickets/EndpointNPlusOneInsightTicket/index.tsx
- src/components/Insights/tickets/NPlusOneInsightTicket/NPlusOneInsightTicket.stories.tsx
- src/components/Insights/tickets/NPlusOneInsightTicket/index.tsx
- src/components/Insights/tickets/types.ts
- src/components/Insights/types.ts
- src/components/common/Button/index.tsx
- src/components/common/Button/types.ts
- src/components/common/ImpactScore/index.tsx
- src/components/common/ImpactScore/styles.ts
- src/components/common/ScoreIndicator/index.tsx
- src/components/common/ScoreIndicator/styles.ts
- src/components/common/ScoreIndicator/types.ts
- src/utils/downloadFile.ts
- src/utils/getCriticalityLabel.ts
Closes #325
Add criticality score for N-Plus-1 insights Closes #316
> Add Jira Ticket for Endpoint N-Plus-1 insight

- src/components/Insights/BottleneckInsight/index.tsx
- src/components/Insights/BottleneckInsight/types.ts
- src/components/Insights/DurationBreakdownInsight/index.tsx
- src/components/Insights/DurationBreakdownInsight/types.ts
- src/components/Insights/DurationSlowdownSourceInsight/index.tsx
- src/components/Insights/DurationSlowdownSourceInsight/types.ts
- src/components/Insights/EndpointNPlusOneInsight/index.tsx
- src/components/Insights/EndpointNPlusOneInsight/types.ts
- src/components/Insights/ErrorsInsight/index.tsx
- src/components/Insights/ErrorsInsight/types.ts
- src/components/Insights/ExcessiveAPICallsInsight/index.tsx
- src/components/Insights/ExcessiveAPICallsInsight/types.ts
- src/components/Insights/InsightList/index.tsx
- src/components/Insights/JiraTicket/JiraTicket.stories.tsx
- src/components/Insights/NPlusOneInsight/index.tsx
- src/components/Insights/NPlusOneInsight/types.ts
- src/components/Insights/ScalingIssueInsight/index.tsx
- src/components/Insights/ScalingIssueInsight/types.ts
- src/components/Insights/SessionInViewInsight/index.tsx
- src/components/Insights/SessionInViewInsight/types.ts
- src/components/Insights/SpanBottleneckInsight/index.tsx
- src/components/Insights/SpanBottleneckInsight/types.ts
- src/components/Insights/TopUsageInsight/index.tsx
- src/components/Insights/TopUsageInsight/types.ts
- src/components/RecentActivity/EnvironmentPanel/index.tsx
- src/components/RecentActivity/EnvironmentPanel/styles.ts
- src/trackingEvents.ts
- src/utils/downloadFile.ts
> Add analytics for the asset links in Insights

- src/components/Insights/HighNumberOfQueriesInsight/HighNumberOfQueriesInsight.stories.tsx
- src/components/Insights/HighNumberOfQueriesInsight/index.tsx
- src/components/Insights/HighNumberOfQueriesInsight/mockData.ts
- src/components/Insights/HighNumberOfQueriesInsight/styles.ts
- src/components/Insights/HighNumberOfQueriesInsight/types.ts
- src/components/Insights/InsightList/index.tsx
- src/components/Insights/Insights.stories.tsx
- src/components/Insights/tickets/BottleneckInsightTicket/index.tsx
- src/components/Insights/tickets/SpanBottleneckInsightTicket/index.tsx
- src/components/Insights/typeGuards.ts
- src/components/Insights/types.ts
- src/types.ts
- src/utils/getInsightTypeInfo.ts
With provided trace ID:
Without provided trace ID:
Expected insight payload from plugin:
https://github.com/digma-ai/digma-collector-backend/issues/1433#issuecomment-1866229557
Closes #338
> Add 'High number of queries' insight

- src/components/Assets/AssetList/AssetEntry/AssetEntry.stories.tsx
- src/components/Assets/AssetList/AssetEntry/index.tsx
- src/components/Assets/AssetList/types.ts
> Added new scope property.

- .eslintrc.js
- src/components/Insights/InsightCard/InsightCard.stories.tsx
- src/components/Insights/InsightCard/index.tsx
- src/components/Insights/tickets/common/CommitInfos/index.tsx
- src/components/InstallationWizard/InstallStep/EngineManager/EngineManager.stories.tsx
- src/components/Tests/index.tsx
- src/components/Tests/styles.ts
> Use page size for tests from the plugin, enforce additional ESLint rules

- src/components/InstallationWizard/InstallStep/index.tsx
> Fix manual installation flow

- src/components/RecentActivity/EnvironmentTypePanel/index.tsx
> Add link to learn more about Digma for teams

- src/components/Insights/ScalingIssueInsight/index.tsx
- src/components/common/InsightsDescription/index.tsx
- src/utils/getInsightTypeInfo.ts
Added criticality 
Added info icon
> Added info icon 

- src/components/Documentation/pages/RunDigma/runDigmaWithCommandLine.tsx
- src/components/Insights/InsightsPage/InsightsPage.stories.tsx
- src/components/Insights/InsightsPage/index.tsx
- src/components/Insights/InsightsPage/types.ts
- src/components/Insights/common/InsightCard/InsightCard.stories.tsx
- src/components/Insights/common/InsightCard/index.tsx
- src/components/Navigation/ScopeBar/ScopeBar.stories.tsx
- src/components/RecentActivity/EnvironmentInstructionsPanel/index.tsx
- src/components/common/App/ConfigContext.ts
- src/components/common/App/types.ts
> Improve empty states in Insights

- src/components/Assets/AssetList/index.tsx
- src/components/Assets/AssetList/styles.ts
- src/components/Assets/AssetList/types.ts
- src/components/Assets/AssetTypeList/AssetTypeListItem/index.tsx
- src/components/Assets/AssetTypeList/AssetTypeListItem/styles.ts
- src/components/Assets/AssetTypeList/index.tsx
- src/components/Assets/AssetTypeList/styles.ts
- src/components/Assets/AssetTypeList/types.ts
- src/components/Assets/AssetsViewScopeConfiguration/AssetsViewScopeConfiguration.stories.tsx
- src/components/Assets/AssetsViewScopeConfiguration/index.tsx
- src/components/Assets/AssetsViewScopeConfiguration/styles.ts
- src/components/Assets/AssetsViewScopeConfiguration/types.ts
- src/components/Assets/index.tsx
- src/components/Assets/styles.ts
- src/components/common/icons/12px/ArrowIcon.tsx
- src/components/common/icons/12px/TreeNodesIcon.tsx
- src/components/common/v3/Toggle/index.tsx
- src/components/common/v3/Toggle/styles.ts
- src/components/common/v3/Toggle/types.ts
> Update Asset View mode toggle, update styles

- src/components/Assets/AssetList/index.tsx
- src/components/Insights/InsightsCatalog/index.tsx
> Show performance impact only for shared environments in Helm deployments

- src/components/Insights/InsightsPage/index.tsx
- src/components/Insights/common/InsightCard/Select/index.tsx
- src/components/Insights/common/InsightCard/index.tsx
- src/components/Insights/common/insights/EndpointBottleneckInsight/index.tsx
- src/components/Insights/common/insights/EndpointBottleneckInsight/styles.ts
- src/components/Insights/common/insights/EndpointChattyApiV2Insight/EndpointChattyApiV2Insight.stories.tsx
- src/components/Insights/common/insights/EndpointChattyApiV2Insight/index.tsx
- src/components/Insights/common/insights/EndpointChattyApiV2Insight/mockData.ts
- src/components/Insights/common/insights/EndpointChattyApiV2Insight/styles.ts
- src/components/Insights/common/insights/EndpointChattyApiV2Insight/types.ts
- src/components/Insights/common/insights/EndpointNPlusOneInsight/index.tsx
- src/components/Insights/common/insights/EndpointNPlusOneInsight/styles.ts
- src/components/Insights/common/insights/EndpointQueryOptimizationInsight/index.tsx
- src/components/Insights/common/insights/EndpointQueryOptimizationV2Insight/EndpointQueryOptimizationV2Insight.stories.tsx
- src/components/Insights/common/insights/EndpointQueryOptimizationV2Insight/index.tsx
- src/components/Insights/common/insights/EndpointQueryOptimizationV2Insight/mockData.ts
- src/components/Insights/common/insights/EndpointQueryOptimizationV2Insight/styles.ts
- src/components/Insights/common/insights/EndpointQueryOptimizationV2Insight/types.ts
- src/components/Insights/common/insights/ScalingIssueInsight/index.tsx
- src/components/Insights/common/insights/SessionInViewInsight/index.tsx
- src/components/Insights/common/insights/SpanQueryOptimizationInsight/index.tsx
- src/components/Insights/index.tsx
- src/components/Insights/tickets/EndpointQueryOptimizationV2InsightTicket/EndpointQueryOptimizationV2InsightTicket.stories.tsx
- src/components/Insights/tickets/EndpointQueryOptimizationV2InsightTicket/index.tsx
- src/components/Insights/typeGuards.ts
- src/components/Insights/types.ts
- src/components/common/v3/Link/styles.ts
- src/types.ts
- src/utils/getInsightTypeInfo.ts
- src/utils/getInsightTypeOrderPriority.ts
> Split EndpointChattyAPI and EndpointQueryOptimization insights

- src/components/Documentation/pages/RunDigma/runDigmaWithCommandLine.tsx
> Fixed typos in maven tags.

- src/components/Insights/styles.ts
- src/components/Tests/styles.ts
Closes https://github.com/digma-ai/digma-ui/issues/532
> Fix Jira ticket styles

- src/components/Insights/InsightsCatalog/InsightsPage/insightCards/EndpointBreakdownInsightCard/index.tsx
- src/components/Insights/deprecated/InsightList/insightCards/RequestBreakdownInsight/index.tsx
- src/components/Insights/types.ts
> Add fallback color for unsupported request types

- src/components/Highlights/TopIssues/index.tsx
> Fix Top Issues carousel

- src/api/index.ts
- src/components/Highlights/Impact/useImpactData.ts
- src/components/Highlights/Performance/usePerformanceData.ts
- src/components/Highlights/Scaling/useScalingData.ts
- src/components/Highlights/SpanInfo/useSpanInfoData.ts
- src/components/Highlights/TopIssues/useTopIssuesData.ts
- src/components/Insights/useInsightsData.ts
- src/components/Navigation/ScopeBar/index.tsx
- src/components/common/v3/Tooltip/styles.ts
Fix highlights refresh Closes #865
Fix tooltip width Closes #611
> Fix highlights refresh

- package-lock.json
- src/api/ActionDispatcher.ts
- src/api/index.ts
- src/api/types.ts
- src/components/Assets/AssetList/index.tsx
- src/components/Assets/AssetTypeList/index.tsx
- src/components/Insights/useInsightsData.ts
> Handle error responses in Assets, Issues and Analytics

- src/components/Main/index.tsx
> Fix history on navigation to Home

- src/components/Assets/AssetList/index.tsx
- src/components/Assets/AssetTypeList/index.tsx
- src/components/Assets/AssetsFilter/index.tsx
- src/components/Assets/AssetsFilter/types.ts
- src/components/Assets/index.tsx
- src/components/Assets/utils.tsx
- src/components/Insights/InsightsCatalog/index.tsx
- src/components/Insights/Issues/IssuesFilter/index.tsx
- src/components/Insights/index.tsx
- src/components/Insights/useInsightsData.ts
- src/components/Main/index.tsx
- src/containers/Main/stores/useGlobalStore.ts
- src/containers/Main/stores/useInsightsStore.ts
> Make service filter global

- src/components/Insights/InsightsCatalog/EnvironmentSelector/EnvironmentChip/index.tsx
- src/components/Insights/InsightsCatalog/EnvironmentSelector/EnvironmentChip/styles.ts
> Add tooltip for environment chips

- src/components/Assets/AssetList/AssetEntry/AssetEntry.stories.tsx
- src/components/Assets/AssetList/AssetEntry/index.tsx
- src/components/Assets/AssetList/mockedData.ts
- src/components/Assets/AssetList/types.ts
> Migrate to new impact score field

- src/components/Insights/InsightsCatalog/EnvironmentSelector/EnvironmentChip/index.tsx
> Change wording for the Environment Chip tooltip

- src/components/Assets/AssetsFilter/index.tsx
> Fix service filter in the Assets

- src/components/Dashboard/NewReport/ReportHeader/index.tsx
- src/components/Dashboard/NewReport/index.tsx
- src/components/Dashboard/NewReport/tracking.ts
- src/components/Dashboard/NewReport/types.ts
- src/components/Dashboard/NewReport/useReportsData.ts
> Report fix

- src/components/Assets/AssetTypeList/AssetTypeList.stories.tsx
- src/components/Assets/AssetTypeList/index.tsx
- src/components/Assets/utils.tsx
> Added new category

- src/components/Dashboard/NewReport/ReportHeader/index.tsx
- src/components/Dashboard/NewReport/ReportHeader/styles.ts
- src/components/common/v3/Checkmark/styles.ts
- src/components/common/v3/Select/Select.stories.tsx
- src/components/common/v3/Select/index.tsx
- src/components/common/v3/Select/styles.ts
- src/components/common/v3/Select/types.ts
> Fix report UI styles

- src/components/Insights/InsightsCatalog/InsightsPage/insightCards/common/InsightCard/index.tsx
> Fix refresh after the recalculation

- src/components/Insights/InsightsCatalog/InsightsPage/AffectedEndpointsSelector/AffectedEndpointsSelector.stories.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/AffectedEndpointsSelector/EndpointOption/index.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/AffectedEndpointsSelector/EndpointOption/styles.ts
> Handel overflow

- src/components/Errors/NewErrorCard/OccurrenceChart/index.tsx
- src/components/Errors/NewErrorCard/OccurrenceChart/styles.ts
- src/components/Insights/InsightsCatalog/InsightsPage/insightCards/SpaNPlusOneInsightCard/index.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/insightCards/SpanEndpointBottleneckInsightCard/index.tsx
- src/components/common/icons/30px/HistogramIcon.tsx
> Restyle Error Occurrence chart empty states, fix affected endpoints selector

- src/components/RecentActivity/LiveView/LiveView.stories.tsx
- src/components/RecentActivity/LiveView/index.tsx
> Fix live view when there is no percentile data

- src/components/Navigation/KebabMenu/index.tsx
- src/components/Navigation/common/MenuList/index.tsx
- src/components/Navigation/common/MenuList/styles.ts
- src/components/Navigation/common/MenuList/types.ts
- src/components/common/icons/12px/MetricsIcon.tsx
> Disable Digma metrics in private environments

- src/components/Insights/InsightsCatalog/InsightsPage/insightCards/common/InsightCard/InsightHeader/InsightStatusTooltipContent/index.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/insightCards/common/IssueCompactCard/index.tsx
> Added status tooltip

- package-lock.json
- package.json
- src/components/IdeLauncher/index.tsx
- src/components/IdeLauncher/scanRunningIdeProjects.ts
- src/components/IdeLauncher/showIdeProject.ts
- src/components/IdeLauncher/styles.ts
- src/components/IdeLauncher/types.ts
> Handle errors in IDE Plugin launcher

- .github/workflows/release.yml
- src/components/common/v3/Select/index.tsx
Attach assets to the Github release
> Make Select searchable if there are more than 10 items

- src/components/Navigation/SpanInfo/index.tsx
- src/components/Navigation/SpanInfo/styles.ts
- src/components/Navigation/SpanInfo/types.ts
- src/components/Navigation/index.tsx
- src/components/common/icons/16px/GearInGearIcon.tsx
> Show instrumentation library in Scope bar

- src/components/Insights/InsightTicketRenderer/insightTickets/EndpointSpanNPlusOneInsightTicket/index.tsx
- src/components/Insights/InsightTicketRenderer/insightTickets/SpaNPlusOneInsightTicket/index.tsx
- src/components/Insights/InsightTicketRenderer/insightTickets/common/getNPlusOneInsightTypeName.ts
- src/components/RecentActivity/Digmathon/getDigmathonInsightData.tsx
- src/utils/getInsightTypeInfo.ts
> Rename insight types

- src/components/Insights/InsightTicketRenderer/insightTickets/SpanQueryOptimizationInsightTicket/index.tsx
> Add related code locations to SpanQueryOptimization insight ticket

- src/components/Admin/common/MainSidebarOverlay/MainSidebar/Analytics/index.tsx
- src/components/Admin/common/MainSidebarOverlay/MainSidebar/Analytics/styles.ts
- src/components/Admin/common/MainSidebarOverlay/MainSidebar/Analytics/types.ts
- src/components/Admin/common/MainSidebarOverlay/MainSidebar/Assets/index.tsx
- src/components/Admin/common/MainSidebarOverlay/MainSidebar/Assets/types.ts
- src/components/Admin/common/MainSidebarOverlay/MainSidebar/Header/index.tsx
- src/components/Admin/common/MainSidebarOverlay/MainSidebar/Header/types.ts
- src/components/Admin/common/MainSidebarOverlay/MainSidebar/Issues/index.tsx
- src/components/Admin/common/MainSidebarOverlay/MainSidebar/index.tsx
- src/components/Admin/common/MainSidebarOverlay/MainSidebar/types.ts
- src/components/Admin/common/MainSidebarOverlay/index.tsx
- src/components/Admin/tracking.ts
- src/components/Insights/InsightsCatalog/InsightsPage/EmptyState/index.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/EmptyState/types.ts
- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/insightCards/common/InsightCard/index.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/insightCards/common/InsightCard/types.ts
- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/insightCards/types.ts
- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/types.ts
- src/components/Insights/InsightsCatalog/InsightsPage/InsightsPage.stories.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/index.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/types.ts
- src/components/Insights/InsightsCatalog/index.tsx
- src/components/Insights/tracking.ts
- src/components/Main/index.tsx
- src/components/Navigation/Tabs/index.tsx
- src/components/common/ErrorScreen/index.tsx
- src/redux/services/types.ts
- src/store/useStore.ts
- src/utils/actions/changeScope.ts
> Add Analytics tab to the Web

- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/insightCards/EndpointQueryOptimizationV2InsightCard/index.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/insightCards/SpanQueryOptimizationInsightCard/index.tsx
> Update wording in Inefficient Query insight

- src/components/common/IssuesReport/Header/index.tsx
- src/featureFlags.ts
- src/types.ts
> Rename Changes tab in Metrics Report

- apps.ts
- src/components/RecentActivity/RecentActivityTable/index.tsx
- src/components/RecentActivity/index.tsx
- src/components/RecentActivity/styles.ts
- src/components/RecentActivity/useRecentActivityData.ts
- src/containers/RecentActivity/store.ts
- src/globals.d.ts
- src/redux/services/plugin.ts
> Add plugin API

- dependencies.json
- src/components/Main/index.tsx
- src/components/RecentActivity/index.tsx
- src/components/RecentActivity/useRecentActivityData.ts
- src/components/common/App/index.tsx
- src/containers/RecentActivity/hooks.ts
- src/redux/services/digma.ts
> Set method id to the search on Hotspot code lens navigation

- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/insightCards/common/InsightCard/InsightHeader/InsightIcon/GradientProgressBar/index.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/insightCards/common/InsightCard/InsightHeader/InsightIcon/GradientProgressBar/styles.ts
- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/insightCards/common/InsightCard/InsightHeader/InsightIcon/GradientProgressBar/types.ts
- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/insightCards/common/InsightCard/InsightHeader/InsightIcon/InsightIconTooltip/index.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/insightCards/common/InsightCard/InsightHeader/InsightIcon/InsightIconTooltip/styles.ts
- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/insightCards/common/InsightCard/InsightHeader/InsightIcon/InsightIconTooltip/types.ts
- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/insightCards/common/InsightCard/InsightHeader/InsightIcon/getValueLabel.ts
- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/insightCards/common/InsightCard/InsightHeader/InsightIcon/index.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/insightCards/common/InsightCard/InsightHeader/InsightIcon/styles.ts
- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/insightCards/common/InsightCard/InsightHeader/InsightIcon/types.ts
- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/insightCards/common/InsightCard/InsightHeader/index.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/insightCards/common/IssueCompactCard/index.tsx
> Add Insight metrics tooltip

- src/components/Admin/Header/HeaderContent/EnvironmentSelect/index.tsx
- src/components/Admin/Header/HeaderContent/FilterToolbar/index.tsx
> Fix global filter in Web Admin
