- .storybook/preview-body.html
- src/components/RecentActivity/EnvironmentPanel/EnvironmentTab/styles.ts
- src/components/RecentActivity/EnvironmentPanel/index.tsx
- src/components/RecentActivity/EnvironmentPanel/styles.ts
- src/components/RecentActivity/EnvironmentPanel/types.ts
- src/components/common/ToggleSwitch/styles.ts
> Add carousel to Recent activity

- src/components/InstallationWizard/InstallStep/index.tsx
- src/components/InstallationWizard/InstallStep/types.ts
- src/components/InstallationWizard/index.tsx
Fix analytics event action Closes #60
> Add analytics event for installation method tab click

- src/components/InstallationWizard/FinishStep/index.tsx
- src/components/InstallationWizard/FinishStep/styles.ts
- src/components/InstallationWizard/FinishStep/types.ts
- src/components/InstallationWizard/InstallStep/index.tsx
- src/components/InstallationWizard/index.tsx
- src/components/common/CircleLoader/index.tsx
- src/components/common/CircleLoader/styles.ts
- src/components/common/CircleLoader/types.ts
- src/components/common/Loader/index.tsx
- src/components/common/icons/ChatIcon.tsx
- src/components/common/icons/WarningCircleLargeIcon.tsx
- src/components/common/icons/hooks.ts
> Add email validation indication to the Wizard

- src/components/InstallationWizard/FinishStep/index.tsx
> Open Getting started video in default browser

- .storybook/preview-body.html
- assets/assets/index.ejs
- src/components/Assets/AssetList/index.tsx
- src/components/Assets/AssetList/styles.ts
- src/components/common/App/index.tsx
- src/globals.d.ts
> Add env variable for the assets search

- src/components/RecentActivity/LiveView/LiveView.stories.tsx
- src/components/RecentActivity/LiveView/index.tsx
> Fix Y Axis scale when data is outside of P50 - P95 area

- src/components/InstallationWizard/InstallStep/index.tsx
Enable the Next button on the Install step (not the first launch) even if Digma Engine is not installed
> Enable Next button on Install step even if Digma Engine is not installed

- src/components/Assets/AssetList/AssetEntry/AssetEntry.stories.tsx
- src/components/Assets/AssetList/AssetEntry/index.tsx
- src/components/Assets/AssetList/AssetEntry/styles.ts
- src/components/Assets/index.tsx
- src/components/Assets/styles.ts
- src/components/Documentation/Page.tsx
- src/components/RecentActivity/index.tsx
- src/components/RecentActivity/styles.ts
- src/components/Troubleshooting/index.tsx
- src/components/common/EmptyState/index.tsx
- src/components/common/EmptyState/styles.ts
- src/components/common/EmptyState/types.ts
- src/components/common/icons/CardsIcon.tsx
- src/trackingEvents.ts
Closes #172 
Add analytics events for Troubleshooting link click and Troubleshooting page loading
> Update text and styles of No Data screens

- src/components/Assets/AssetList/index.tsx
- src/components/RecentActivity/index.tsx
- src/components/RecentActivity/styles.ts
Closes #175
Closes #176 
Update styles
> Fix asset sorting and filtering

- src/components/Insights/DurationInsight/index.tsx
- src/components/Insights/types.ts
> Set minimal bar height

- src/components/Insights/EndpointNPlusOneInsight/EndpointNPlusOneInsight.stories.tsx
- src/components/Insights/types.ts
- src/components/Notifications/index.tsx
- src/components/RecentActivity/EnvironmentInstructionsPanel/index.tsx
- src/components/RecentActivity/EnvironmentInstructionsPanel/styles.ts
- src/components/RecentActivity/RecentActivityTable/styles.ts
- src/components/RecentActivity/index.tsx
- src/components/RecentActivity/styles.ts
- src/components/common/App/styles.ts
- src/components/common/NewPopover/index.tsx
- src/components/common/Tooltip/styles.ts
> Make Recent activity environment panel sticky

- src/components/Documentation/pages/EnvironmentTypes/EnvironmentTypeCard/styles.ts
- src/components/Documentation/pages/EnvironmentTypes/InsightCard/styles.ts
- src/components/Documentation/pages/EnvironmentTypes/index.tsx
- src/components/Documentation/pages/EnvironmentTypes/styles.ts
- src/components/Documentation/pages/EnvironmentTypes/types.ts
> Update Insights Overview styles

- src/components/Insights/EndpointNPlusOneInsight/index.tsx
- src/components/Insights/EndpointNPlusOneInsight/types.ts
- src/components/Insights/ExcessiveAPICallsInsight/index.tsx
- src/components/Insights/ExcessiveAPICallsInsight/types.ts
- src/components/Insights/InsightList/index.tsx
- src/components/Insights/NPlusOneInsight/index.tsx
- src/components/Insights/NPlusOneInsight/types.ts
- src/components/Insights/ScalingIssueInsight/index.tsx
- src/components/Insights/ScalingIssueInsight/types.ts
- src/components/Insights/SessionInViewInsight/index.tsx
- src/components/Insights/SessionInViewInsight/types.ts
- src/components/Insights/TopUsageInsight/index.tsx
- src/components/Insights/TopUsageInsight/types.ts
> Add spanCodeObjectId to GO_TO_TRACE message

- src/components/Assets/FilterMenu/index.tsx
- src/components/Assets/FilterMenu/styles.ts
- src/components/Assets/FilterMenu/types.ts
- src/components/Assets/index.tsx
- src/components/Assets/styles.ts
> Add loader to service filter in Assets

- src/components/Assets/AssetList/AssetEntry/index.tsx
- src/components/Assets/AssetList/index.tsx
- src/components/Assets/index.tsx
- src/components/Dashboard/index.tsx
- src/components/common/ImpactScore/index.tsx
- src/featureFlags.ts
- src/types.ts
> Hide Overall Impact score

- src/components/Insights/HighNumberOfQueriesInsight/index.tsx
- src/components/Insights/HighNumberOfQueriesInsight/mockData.ts
- src/components/Insights/types.ts
> Added additional info for many queries insights

- src/components/Insights/InsightCard/index.tsx
- src/components/Insights/SpanNexusInsight/index.tsx
- src/components/Insights/SpanNexusInsight/mockData.ts
- src/components/Insights/types.ts
- src/components/common/Tag/types.ts
* Changed criteria for recalculating description 
* Removed usage block
* Added dynamic styling for flos/endpoints/services blocks
* Fixed typo
> Code nexus styles

- src/components/Assets/AssetTypeList/AssetTypeList.stories.tsx
- src/components/Assets/AssetTypeList/index.tsx
- src/components/Assets/AssetTypeList/styles.ts
- src/components/Assets/NoDataMessage/NoDataMessage.stories.tsx
- src/components/Assets/NoDataMessage/index.tsx
- src/components/Assets/NoDataMessage/styles.ts
- src/components/Assets/NoDataMessage/types.ts
- src/components/Assets/index.tsx
> Fix Assets initial screen

- src/components/Insights/EndpointNPlusOneInsight/index.tsx
- src/components/Insights/EndpointQueryOptimizationInsight/index.tsx
- src/components/Insights/SpanBottleneckInsight/index.tsx
> Show only single hint per insight card

- package-lock.json
- package.json
- src/components/Insights/BottleneckInsight/mockData.ts
- src/components/Insights/DurationBreakdownInsight/DurationBreakdownInsight.stories.tsx
- src/components/Insights/DurationInsight/DurationInsight.stories.tsx
- src/components/Insights/DurationSlowdownSourceInsight/DurationSlowdownSourceInsight.stories.tsx
- src/components/Insights/EndpointNPlusOneInsight/mockData.ts
- src/components/Insights/EndpointQueryOptimizationInsight/mockData.ts
- src/components/Insights/ErrorsInsight/ErrorsInsight.stories.tsx
- src/components/Insights/ExcessiveAPICallsInsight/ExcessiveAPICallsInsight.stories.tsx
- src/components/Insights/HighNumberOfQueriesInsight/mockData.ts
- src/components/Insights/InsightCard/InsightCard.stories.tsx
- src/components/Insights/InsightJiraTicket/InsightJiraTicket.stories.tsx
- src/components/Insights/Insights.stories.tsx
- src/components/Insights/InsightsPage/index.tsx
- src/components/Insights/NPlusOneInsight/mockData.ts
- src/components/Insights/NoScalingIssueInsight/NoScalingIssueInsight.stories.tsx
- src/components/Insights/PerformanceAtScaleInsight/PerformanceAtScaleInsight.stories.tsx
- src/components/Insights/QueryOptimizationInsight/mockData.ts
- src/components/Insights/RequestBreakdownInsight/RequestBreakdownInsight.stories.tsx
- src/components/Insights/ScalingIssueInsight/ScalingIssueInsight.stories.tsx
- src/components/Insights/SessionInViewInsight/SessionInViewInsight.stories.tsx
- src/components/Insights/SlowEndpointInsight/SlowEndpointInsight.stories.tsx
- src/components/Insights/SpanBottleneckInsight/mockData.ts
- src/components/Insights/SpanNexusInsight/mockData.ts
- src/components/Insights/TopUsageInsight/TopUsageInsight.stories.tsx
- src/components/Insights/TrafficInsight/TrafficInsight.stories.tsx
- src/components/Insights/types.ts
- src/components/common/v3/Card/Card.stories.tsx
- src/components/common/v3/Card/styles.ts
Improve Card
Remove uuid package
> Improve card

- src/components/Assets/index.tsx
- src/components/Insights/index.tsx
- src/components/Navigation/EnvironmentBar/types.ts
- src/components/Navigation/ScopeNavigation/index.tsx
- src/components/Navigation/index.tsx
- src/components/Navigation/types.ts
- src/components/common/App/index.tsx
- src/components/common/App/types.ts
> Fix env empty state

- src/components/Insights/EndpointNPlusOneInsight/mockData.ts
- src/components/Insights/common/InsightCard/InsightHeader/InisghtHeader.stories.tsx
- src/components/Insights/common/InsightCard/InsightHeader/InsightStatusBadge/InsightStatusBadge.stories.tsx
- src/components/Insights/common/InsightCard/InsightHeader/InsightStatusBadge/getInsightStatusInfo.ts
- src/components/Insights/common/InsightCard/InsightHeader/InsightStatusBadge/index.tsx
- src/components/Insights/common/InsightCard/InsightHeader/InsightStatusBadge/styles.ts
- src/components/Insights/common/InsightCard/InsightHeader/InsightStatusBadge/types.ts
- src/components/Insights/common/InsightCard/InsightHeader/index.tsx
- src/components/Insights/common/InsightCard/InsightHeader/styles.ts
- src/components/Insights/common/InsightCard/InsightHeader/types.ts
- src/components/Insights/common/InsightCard/index.tsx
- src/components/Insights/types.ts
> Add insight status

- src/components/RecentActivity/EnvironmentTypePanel/index.tsx
- src/components/common/App/types.ts
> Enable Shared environment creation if deployment is Helm

- src/components/Assets/AssetList/AssetEntry/index.tsx
- src/components/Assets/AssetList/AssetEntry/styles.ts
- src/components/Assets/AssetList/AssetEntry/types.ts
- src/components/Assets/AssetList/index.tsx
- src/components/RecentActivity/EnvironmentTypePanel/index.tsx
Closes #542 
Move the scope to the top of the Asset card Closes #403
> Hide Performance impact and corresponding sorting criterion

- src/components/Insights/InsightsCatalog/index.tsx
- src/components/Insights/common/InsightCard/Select/index.tsx
- src/components/Insights/common/InsightCard/Select/styles.ts
> Restrict sorting in Analytics tab

- src/components/Insights/common/insights/EndpointBottleneckInsight/index.tsx
- src/components/Insights/common/insights/SpanEndpointBottleneckInsight/index.tsx
> Update Bottleneck insights description

- src/components/RecentActivity/EnvironmentInstructionsPanel/index.tsx
- src/constants.ts
> Update link for central installation guide

- package-lock.json
- package.json
- src/components/Main/RegistrationCard/index.tsx
- src/components/RecentActivity/CreateEnvironmentWizard/RegisterStep/index.tsx
- src/components/RecentActivity/CreateEnvironmentWizard/index.tsx
- src/components/Tests/TestCard/index.tsx
- src/components/common/App/index.tsx
- src/components/common/ErrorScreen/ErrorScreen.stories.tsx
- src/components/common/ErrorScreen/index.tsx
- src/components/common/ErrorScreen/styles.ts
- src/containers/Dashboard/index.tsx
- src/containers/Documentation/index.tsx
- src/containers/InstallationWizard/index.tsx
- src/containers/Main/index.tsx
- src/containers/Main/router.tsx
- src/containers/Notifications/index.tsx
- src/containers/RecentActivity/index.tsx
- src/containers/Troubleshooting/index.tsx
- src/trackingEvents.ts
- src/utils/actions/sendErrorTrackingEvent.ts
- src/utils/handleUncaughtError.ts
> Add error handling

- src/components/Main/Authentication/index.tsx
- src/components/Main/index.tsx
- src/components/Main/tracking.ts
- src/trackingEvents.ts
> Add tracking events for user info change and login screen

- src/components/Highlights/common/TableInsightStatusBadge/index.tsx
- src/components/Highlights/common/TableInsightStatusBadge/styles.ts
- src/components/Insights/InsightsCatalog/InsightsPage/insightCards/common/InsightCard/InsightHeader/index.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/insightCards/common/InsightStatusBadge/InsightStatusBadge.stories.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/insightCards/common/InsightStatusBadge/getInsightStatusInfo.ts
- src/components/Insights/InsightsCatalog/InsightsPage/insightCards/common/InsightStatusBadge/index.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/insightCards/common/InsightStatusBadge/styles.ts
- src/components/Insights/InsightsCatalog/InsightsPage/insightCards/common/InsightStatusBadge/types.ts
- src/components/Insights/InsightsCatalog/InsightsPage/insightCards/common/IssueCompactCard/index.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/insightCards/common/IssueCompactCard/styles.ts
> Add status indicator to the Insight Compact card

- src/components/Navigation/ScopeBar/LinkedEndpointsMenu/LinkedEndpointsMenu.stories.tsx
- src/components/Navigation/ScopeBar/LinkedEndpointsMenu/index.tsx
- src/components/Navigation/ScopeBar/LinkedEndpointsMenu/styles.ts
- src/components/Navigation/ScopeBar/LinkedEndpointsMenu/types.ts
- src/components/Navigation/ScopeBar/ScopeBar.stories.tsx
- src/components/Navigation/ScopeBar/index.tsx
- src/components/Navigation/ScopeBar/styles.ts
- src/components/Navigation/ScopeBar/types.ts
- src/components/Navigation/SpanInfo/types.ts
- src/components/Navigation/index.tsx
- src/components/Navigation/tracking.ts
- src/components/common/icons/14px/ChainIcon.tsx
> Added linked endpoints

- src/components/Errors/ErrorDetails/ErrorDetailsCardContent/FlowStack/index.tsx
- src/components/Errors/NewErrorCard/OccurrenceChart/index.tsx
- src/components/Errors/NewErrorCard/OccurrenceChart/styles.ts
- src/components/Errors/index.tsx
- src/store/errors/errorsSlice.ts
> Fix "Workspace only" toggle value persistence

- src/components/Assets/AssetList/AssetList.stories.tsx
- src/components/Assets/AssetList/index.tsx
- src/components/Assets/AssetList/types.ts
- src/components/Assets/AssetTypeList/AssetTypeList.stories.tsx
- src/components/Assets/AssetTypeList/index.tsx
- src/components/Assets/AssetTypeList/types.ts
- src/components/Assets/index.tsx
- src/hooks/useFetchData.test.ts
- src/hooks/useFetchData.ts
> Fix flickering

- src/components/Assets/AssetList/AssetEntry/AssetEntry.stories.tsx
- src/components/Assets/AssetList/AssetEntry/index.tsx
- src/components/common/ImpactScore/index.tsx
> Format impact score

- src/components/Errors/NewErrorCard/index.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/insightCards/SpaNPlusOneInsightCard/index.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/insightCards/SpanEndpointBottleneckInsightCard/index.tsx
- src/components/common/AffectedEndpointsSelector/index.tsx
- src/components/common/AffectedEndpointsSelector/types.ts
> Fix Affected Endpoints select

- src/components/Admin/Home/Overview/styles.ts
- src/components/Insights/InsightTicketRenderer/insightTickets/SpanPerformanceAnomalyInsightTicket/index.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/index.tsx
- src/components/Insights/InsightsCatalog/InsightsPage/InsightCardRenderer/insightCards/SpanPerformanceAnomalyInsightCard/SpanPerformanceAnomalyInsightCard.stories.tsx
> Fix overview widget placeholder size

- src/components/Agentic/IncidentDetails/AgentEvents/index.tsx
- src/components/Agentic/IncidentDetails/IncidentMetaData/index.tsx
- src/components/Agentic/common/AgentChat/index.tsx
> Format incident status

- src/components/Agentic/IncidentDetails/AgentFlowChart/AgentFlowChartNodeToolbar/index.tsx
- src/components/Agentic/IncidentDetails/AgentFlowChart/AgentFlowChartNodeToolbar/types.ts
- src/components/Agentic/IncidentDetails/AgentFlowChart/MCPServersToolbar/index.tsx
- src/components/Agentic/IncidentDetails/AgentFlowChart/MCPServersToolbar/types.ts
- src/components/Agentic/IncidentDetails/AgentFlowChart/index.tsx
- src/components/Agentic/IncidentDetails/AgentFlowChart/types.ts
- src/components/Agentic/IncidentTemplate/MCPServerDialog/index.tsx
- src/components/Agentic/IncidentTemplate/index.tsx
- src/components/Errors/ErrorDetails/ErrorDetailsCardContent/FlowStack/index.tsx
- src/components/Errors/ErrorDetails/ErrorDetailsCardContent/FlowStack/types.ts
- src/components/Errors/ErrorDetails/ErrorDetailsCardContent/index.tsx
- src/components/Errors/NewErrorCard/index.tsx
- src/components/Errors/tracking.ts
- src/redux/services/types.ts
Add Open in IDE button for errors
> Do not show JSON on Edit MCP server

- src/components/Agentic/IncidentTemplate/index.tsx
- src/components/Agentic/IncidentTemplate/styles.ts
- src/components/Errors/EmptyState/index.tsx
- src/components/Errors/GlobalErrorsList/styles.ts
- src/components/Insights/InsightsCatalog/InsightsPage/EmptyState/index.tsx
- src/components/Insights/InsightsCatalog/styles.ts
- src/components/RecentActivity/CreateEnvironmentWizard/ErrorsPanel/ErrorCard/index.tsx
- src/components/RecentActivity/CreateEnvironmentWizard/ErrorsPanel/ErrorCard/styles.ts
- src/components/common/AffectedEndpointsSelector/EndpointOption/index.tsx
- src/components/common/AffectedEndpointsSelector/EndpointOption/styles.ts
- src/components/common/AffectedEndpointsSelector/EndpointOption/types.ts
- src/components/common/AffectedEndpointsSelector/index.tsx
- src/components/common/AffectedEndpointsSelector/styles.ts
Closes #673
Closes #1001
Closes #703
Closes #1409
> Improve styles

- src/components/Admin/common/RepositorySidebarOverlay/index.tsx
- src/components/Insights/hooks/useInsightsData.ts
- src/components/Insights/hooks/useInsightsStats.ts
> Fix service filter in sidebar

- src/components/Agentic/IncidentDetails/AgentFlowChart/AgentFlowChartNodeToolbar/index.tsx
- src/components/Agentic/IncidentDetails/AgentFlowChart/AgentFlowChartNodeToolbar/types.ts
- src/components/Agentic/IncidentDetails/AgentFlowChart/MCPServersToolbar/index.tsx
- src/components/Agentic/IncidentDetails/AgentFlowChart/MCPServersToolbar/types.ts
- src/components/Agentic/IncidentDetails/AgentFlowChart/index.tsx
- src/components/Agentic/IncidentDetails/AgentFlowChart/types.ts
- src/components/Agentic/IncidentTemplate/MCPServerDialog/index.tsx
- src/components/Agentic/IncidentTemplate/index.tsx
- src/redux/services/types.ts
> Open second step of MCP dialog on edit click

- .vscode/launch.json
- src/components/Admin/common/RepositorySidebarOverlay/RepositorySidebar/Analytics/index.tsx
- src/components/Admin/common/RepositorySidebarOverlay/RepositorySidebar/Analytics/types.ts
- src/components/Admin/common/RepositorySidebarOverlay/RepositorySidebar/Assets/index.tsx
- src/components/Admin/common/RepositorySidebarOverlay/RepositorySidebar/Assets/types.ts
- src/components/Admin/common/RepositorySidebarOverlay/RepositorySidebar/Errors/index.tsx
- src/components/Admin/common/RepositorySidebarOverlay/RepositorySidebar/Issues/index.tsx
- src/components/Admin/common/RepositorySidebarOverlay/index.tsx
- src/components/Dashboard/MetricsReport/index.tsx
- src/components/common/IssuesReport/index.tsx
- src/store/errors/errorsSlice.ts
> Fix filters

- Dockerfile
- openapi-config.ts
- package-lock.json
- package.json
- src/components/Agentic/IncidentDetails/AgentFlowChart/MCPServerIcon/index.tsx
- src/components/Agentic/IncidentDetails/AgentFlowChart/MCPServerIcon/styles.ts
- src/components/Agentic/IncidentDetails/AgentFlowChart/MCPServerIcon/types.ts
- src/components/Agentic/IncidentDetails/AgentFlowChart/MCPServersContainer/index.tsx
- src/components/Agentic/IncidentDetails/AgentFlowChart/MCPServersToolbar/index.tsx
- src/components/Agentic/IncidentDetails/AgentFlowChart/MCPServersToolbar/styles.ts
- src/components/Agentic/IncidentTemplate/MCPServerDialog/ToolsStep/index.tsx
- src/components/Agentic/IncidentTemplate/MCPServerDialog/ToolsStep/styles.ts
- src/components/Agentic/IncidentTemplate/MCPServerDialog/ToolsStep/types.ts
- src/components/Agentic/IncidentTemplate/MCPServerDialog/index.tsx
- src/components/Agentic/IncidentTemplate/index.tsx
- src/components/Agentic/common/PromptInput/index.tsx
- src/components/common/icons/12px/DownloadIcon.tsx
- src/components/common/icons/32px/PageIcon.tsx
- src/hooks/useFormDataRequest.ts
- src/redux/services/types.ts
> Support custom MCP server icons
